import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

df = pd.read_csv(r'D:\Data analyst price stock\Apple price stock\AAPL_cleaned.csv')
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date').reset_index(drop=True)

df['MA50'] = df['Close'].rolling(window=50).mean()
df['MA200'] = df['Close'].rolling(window=200).mean()

fig1, ax1 = plt.subplots(figsize=(14, 7))
ax1.plot(df['Date'], df['Close'], color='#1f77b4', linewidth=0.8, label='Close Price')
ax1.set_xlabel('Date', fontsize=12)
ax1.set_ylabel('Closing Price (USD)', fontsize=12)
ax1.set_title('Apple (AAPL) Stock Closing Price Over Time', fontsize=14, fontweight='bold')
ax1.xaxis.set_major_locator(mdates.YearLocator(5))
ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.xticks(rotation=45)
ax1.grid(True, alpha=0.3)
ax1.legend(loc='upper left')
plt.tight_layout()
plt.savefig(r'D:\Data analyst price stock\Apple price stock\AAPL_closing_price.png', dpi=150, bbox_inches='tight')
plt.close()

fig2, ax2 = plt.subplots(figsize=(14, 7))
ax2.plot(df['Date'], df['Open'], color='#2ca02c', linewidth=0.7, label='Open Price', alpha=0.8)
ax2.plot(df['Date'], df['Close'], color='#1f77b4', linewidth=0.7, label='Close Price', alpha=0.8)
ax2.set_xlabel('Date', fontsize=12)
ax2.set_ylabel('Price (USD)', fontsize=12)
ax2.set_title('Apple (AAPL) - Opening vs Closing Price Over Time', fontsize=14, fontweight='bold')
ax2.xaxis.set_major_locator(mdates.YearLocator(5))
ax2.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.xticks(rotation=45)
ax2.grid(True, alpha=0.3)
ax2.legend(loc='upper left')
plt.tight_layout()
plt.savefig(r'D:\Data analyst price stock\Apple price stock\AAPL_open_close_comparison.png', dpi=150, bbox_inches='tight')
plt.close()

fig3, ax3 = plt.subplots(figsize=(14, 7))
ax3.plot(df['Date'], df['High'], color='#d62728', linewidth=0.7, label='High Price', alpha=0.8)
ax3.plot(df['Date'], df['Low'], color='#ff7f0e', linewidth=0.7, label='Low Price', alpha=0.8)
ax3.fill_between(df['Date'], df['Low'], df['High'], alpha=0.2, color='gray', label='Price Range')
ax3.set_xlabel('Date', fontsize=12)
ax3.set_ylabel('Price (USD)', fontsize=12)
ax3.set_title('Apple (AAPL) - High and Low Prices (Price Range Volatility)', fontsize=14, fontweight='bold')
ax3.xaxis.set_major_locator(mdates.YearLocator(5))
ax3.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.xticks(rotation=45)
ax3.grid(True, alpha=0.3)
ax3.legend(loc='upper left')
plt.tight_layout()
plt.savefig(r'D:\Data analyst price stock\Apple price stock\AAPL_high_low.png', dpi=150, bbox_inches='tight')
plt.close()

fig4, ax4 = plt.subplots(figsize=(14, 7))
ax4.bar(df['Date'], df['Volume'], color='#9467bd', width=2, alpha=0.7)
ax4.set_xlabel('Date', fontsize=12)
ax4.set_ylabel('Trading Volume', fontsize=12)
ax4.set_title('Apple (AAPL) - Trading Volume Over Time', fontsize=14, fontweight='bold')
ax4.xaxis.set_major_locator(mdates.YearLocator(5))
ax4.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.xticks(rotation=45)
ax4.grid(True, alpha=0.3, axis='y')
ax4.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x/1e6:.0f}M'))
plt.tight_layout()
plt.savefig(r'D:\Data analyst price stock\Apple price stock\AAPL_volume.png', dpi=150, bbox_inches='tight')
plt.close()

fig5, ax5 = plt.subplots(figsize=(14, 7))
ax5.plot(df['Date'], df['Close'], color='#1f77b4', linewidth=0.8, label='Close Price', alpha=0.9)
ax5.plot(df['Date'], df['MA50'], color='#2ca02c', linewidth=1, label='50-Day MA', alpha=0.9)
ax5.plot(df['Date'], df['MA200'], color='#d62728', linewidth=1, label='200-Day MA', alpha=0.9)
ax5.set_xlabel('Date', fontsize=12)
ax5.set_ylabel('Price (USD)', fontsize=12)
ax5.set_title('Apple (AAPL) - Closing Price with Moving Averages', fontsize=14, fontweight='bold')
ax5.xaxis.set_major_locator(mdates.YearLocator(5))
ax5.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.xticks(rotation=45)
ax5.grid(True, alpha=0.3)
ax5.legend(loc='upper left')
plt.tight_layout()
plt.savefig(r'D:\Data analyst price stock\Apple price stock\AAPL_moving_averages.png', dpi=150, bbox_inches='tight')
plt.close()

print("All graphs saved to D:\\Data analyst price stock\\Apple price stock\\:")
print("  1. AAPL_closing_price.png")
print("  2. AAPL_open_close_comparison.png")
print("  3. AAPL_high_low.png")
print("  4. AAPL_volume.png")
print("  5. AAPL_moving_averages.png")
print(f"Data range: {df['Date'].min().strftime('%Y-%m-%d')} to {df['Date'].max().strftime('%Y-%m-%d')}")